language: python
sudo: false
addons:
  apt:
    packages:
    - luarocks
before_install:
  - luarocks install --local luacheck && luarocks install --local busted
  - pip3 install pre-commit
script:
  - pre-commit run --all-files
  - $HOME/.luarocks/bin/luacheck .
  - $HOME/.luarocks/bin/busted .
notifications:
  email: false
