---
name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  busted:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: louisroyer-gh-actions/busted@v1.2.0
        with:
          args: .
